[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit SSD1306@^2.5.7 ; OLED 显示屏库
  adafruit/Adafruit GFX Library@^1.11.9 ; OLED 图形库
  adafruit/Adafruit NeoPixel @ ^1.12.3 ; RGB LED
  keypad@^3.1.1 ; 按键矩阵库